NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
VERSION = "2.0.0"

ACCOUNTS = [
  "GBPN2SUOMV22OGTQD66GJYX5OSAVFKNMS3O5ZJISGMM3CE2CAY3HZLG2"
]

[DOCUMENTATION]
ORG_NAME = "MonregalCoin"
ORG_URL  = "https://hacklabmondovi.it"
ORG_DESCRIPTION = "Valuta locale digitale di Mondovì"

[[CURRENCIES]]
code = "MONREGALCOIN"
issuer = "GBPN2SUOMV22OGTQD66GJYX5OSAVFKNMS3O5ZJISGMM3CE2CAY3HZLG2"
name  = "MonregalCoin"
desc  = "Valuta locale digitale di Mondovì"
conditions = "Distribuita dal team MonregalCoin"
display_decimals = 2
image = "https://www.hacklabmondovi.it/wp-content/uploads/2025/08/logo.png"
