NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

[[CURRENCIES]]
code="MONREGALCOIN"
issuer="GBPN2SUOMV22OGTQD66GJYX5OSAVFKNMS3O5ZJISGMM3CE2CAY3HZLG2"
display_decimals=2
name="MonregalCoin"
desc="Valuta locale digitale di Mondovi, per progetti civici e comunitari."
image="https://www.hacklabmondovi.it/wp-content/uploads/2025/08/logo.png"
conditions="Distribuita dal team MonregalCoin in modo etico e trasparente"
